version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    reviewers:
      - "bajtos"
      - "juliangruber"
    ignore:
      # For Deno crates, ignore all semver-minor updates
      # More often than not, these crates must be updated together,
      # and Dependabot cannot do that yet (see https://github.com/github/roadmap/issues/148)
      dependency-name: "deno_*"
      update-types: ["version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "ci"
    reviewers:
      - "bajtos"
      - "juliangruber"
