[workspace]
resolver = "2"
members = [
  "cli",
]

[workspace.package]
edition = "2021"
rust-version = "1.66.0"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs"]
repository = "https://github.com/filecoin-station/zinnia"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 3
