[workspace]
resolver = "2"
members = [
  "ext/libp2p",

  "runtime",
  "cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs"]
repository = "https://github.com/filecoin-station/zinnia"

[workspace.dependencies]
tokio = { version = "1.24.1", features = ["fs", "rt", "macros"] }
assert_fs = "1.0.10"
pretty_assertions = "1.3.0"
deno_core = "0.171.0"

# workspace-local
zinnia_runtime = { version = "0.0.3", path = "./runtime" }
zinnia_libp2p = { version = "0.0.3", path = "./ext/libp2p" }

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
