[workspace]
resolver = "2"
members = [
    "ext/libp2p",

    "runtime",
    "cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs"]
repository = "https://github.com/filecoin-station/zinnia"

[workspace.dependencies]
assert_fs = "1.0.10"
deno_core = "0.174.0"
log = "0.4.17"
pretty_assertions = "1.3.0"
env_logger = "0.10.0"
tokio = { version = "1.24.1", features = ["fs", "rt", "macros"] }

# workspace-local
zinnia_runtime = { version = "0.2.0", path = "./runtime" }
zinnia_libp2p = { version = "0.2.0", path = "./ext/libp2p" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
