[workspace]
resolver = "2"
members = [
  "runtime",
  "cli",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs"]
repository = "https://github.com/filecoin-station/zinnia"

[workspace.dependencies]
tokio = { version = "1.24.1", features = ["fs", "rt", "macros"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 3
