[target.x86_64-unknown-linux-gnu]
pre-build = [
    "rm -rf /usr/local/go && curl -L https://go.dev/dl/go1.20.5.linux-amd64.tar.gz | sudo tar -xz -C /usr/local",
    "export PATH=$PATH:/usr/local/go/bin",
    "go version"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "rm -rf /usr/local/go && curl -L https://go.dev/dl/go1.20.5.linux-arm64.tar.gz | sudo tar -xz -C /usr/local",
    "export PATH=$PATH:/usr/local/go/bin",
    "go version"
]
