[package]
name = "zinnia_runtime"
version = "0.0.0"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zinnia is a runtime for Filecoin Station modules. This crate provides the runtime including all platform APIs."

[lib]
name = "zinnia_runtime"
path = "lib.rs"

[dependencies]
deno_runtime = "0.97.0"
tokio = { workspace = true, features = ["fs"] }

# [dev-dependencies]
# assert_cmd = "2.0.8"
# assert_fs = "1.0.10"
# pretty_assertions = "1.3.0"
