[package]
name = "zinnia_runtime"
version = "0.13.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zinnia is a runtime for Filecoin Station modules. This crate provides the runtime including all platform APIs."

[lib]
name = "zinnia_runtime"
path = "lib.rs"

[dependencies]
atty = "0.2.14"
chrono = { version= "0.4.26", default-features = false, features = [ "clock", "std" ] }
deno_console = "0.108.0"
deno_core.workspace = true
deno_crypto = "0.122.0"
deno_fetch = "0.132.0"
deno_url = "0.108.0"
deno_web = "0.139.0"
deno_webidl = "0.108.0"
lassie = "0.5.1"
# lassie = { git = "https://github.com/filecoin-station/rusty-lassie.git" }
log.workspace = true
once_cell = "1.18.0"
serde.workspace = true
serde_repr.workspace = true
termcolor = "1.2.0"
tokio = { workspace = true, features = ["fs"] }
zinnia_libp2p.workspace = true

[dev-dependencies]
assert_fs = { workspace = true }
console_static_text = "0.8.1"
env_logger.workspace = true
pretty_assertions = { workspace = true }
regex = "1.8.4"
