[package]
name = "zinnia_runtime"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zinnia is a runtime for Filecoin Station modules. This crate provides the runtime including all platform APIs."

[lib]
name = "zinnia_runtime"
path = "lib.rs"

[dependencies]
atty = "0.2.14"
chrono = { version= "0.4.24", default-features = false, features = [ "clock", "std" ] }
deno_console = "0.98.0"
deno_core.workspace = true
deno_crypto = "0.112.0"
deno_fetch = "0.122.0"
deno_url = "0.98.0"
deno_web = "0.129.0"
deno_webidl = "0.98.0"
log.workspace = true
once_cell = "1.17.1"
serde.workspace = true
serde_repr.workspace = true
termcolor = "1.2.0"
tokio = { workspace = true, features = ["fs"] }
zinnia_libp2p.workspace = true

[dev-dependencies]
env_logger.workspace = true
pretty_assertions = { workspace = true }
