[package]
name = "zinniad"
version = "0.12.0"
authors.workspace = true
default-run = "zinniad"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zinnia daemon runs Zinnia modules inside Filecoin Station."

[[bin]]
name = "zinniad"
path = "main.rs"
doc = false

[dependencies]
atomicwrites = "0.4.1"
clap = { version = "4.3.8", features = ["derive", "env"] }
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json = "1.0.99"
tokio = { workspace = true }
zinnia_runtime = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = "3.6.0"
