# See https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example
[advisories]
ignore = [
  # Marvin Attack: potential key recovery through timing sidechannels
  # We don't share any RSA keys with Zinnia modules
  "RUSTSEC-2023-0071",
  # paste - no longer maintained
  # This is a dependency of Deno/v8, we have to wait for Deno to fix this
  "RUSTSEC-2024-0436"
]
