name: Security audit
on:
  push:
    paths:
      - '.cargo/audit.toml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install cargo-audit
      - run: cargo audit
