name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  MACOSX_DEPLOYMENT_TARGET: 10.7
  # Emit backtraces on panics.
  RUST_BACKTRACE: 1

jobs:
  github_build:
    name: Build ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # List of platforms, this must be in sync with the list of platforms in ci.yaml
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: zinnia-linux-x64.tar.gz

          - target: x86_64-apple-darwin
            os: macos-latest
            name: zinnia-macos-x64.zip

          - target: aarch64-apple-darwin
            os: macos-latest
            name: zinnia-macos-arm64.zip

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: zinnia-windows-x64.zip
            rustflags: -C target-feature=+crt-static -C lto=off
            #                                        ^^^^^^^^^^
            # LTO is temporarily disabled, see https://github.com/rust-lang/rust/issues/107781

    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: ${{ matrix.rustflags || '' }}
    steps:
      - name: Setup | Apple codesign
        if: matrix.os == 'macos-latest'
        env:
          LOCAL_KEYCHAIN_PASSWORD: ${{ secrets.LOCAL_KEYCHAIN_PASSWORD }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: |
          echo -n "$MACOS_CERTIFICATE" | base64 --decode -o certificate.p12
          [ "$MACOS_CERTIFICATE_PASSWORD" = "" ] && echo "WARNING: Certificate passphrase is not set"

          echo "Inspecting the signing certificate:"
          openssl pkcs12 -info -in certificate.p12 -password "pass:$MACOS_CERTIFICATE_PASSWORD" -nokeys | head -7

          echo "Setting up keychain for codesign"
          security create-keychain -p "$LOCAL_KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$LOCAL_KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$LOCAL_KEYCHAIN_PASSWORD" build.keychain
          security list-keychain -d user -s build.keychain

      - name: Setup | Install Protoc
        uses: arduino/setup-protoc@ab6203da1c3118e4406048171b09238ad31ad73e # latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@52e69531e6f69a396bc9d1226284493a5db969ff # v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      # When debugging this workflow, cache the build artefacts
      # Note that a build for one tag cannot access cache created by a build for a different tag,
      # therefore caching does not work for real release builds.
      - name: DEBUGGING | Cache Rust deps
        uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f # v2.2.1
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          shared-key: release-${{ matrix.target }}
          cache-on-failure: true

      - name: Build | Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Post Build | Prepare artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.name }} zinnia.exe
          cd -

      - name: Post Build | Prepare artifacts [Linux]
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.name }} zinnia
          cd -

      - name: Post Build | Sign the executable [macOS]
        if: matrix.os == 'macos-latest'
        env:
          LOCAL_KEYCHAIN_PASSWORD: ${{ secrets.LOCAL_KEYCHAIN_PASSWORD }}
          MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
          MACOS_APP_ID: io.filstation.zinnia
        run: |
          # Unlock the keychain again. Our builds take several minutes to complete,
          # which usually triggers a timeout that locks the keychain.
          security unlock-keychain -p "$LOCAL_KEYCHAIN_PASSWORD" build.keychain

          codesign --timestamp --force --verbose \
            --sign "$MACOS_SIGNING_IDENTITY" \
            --identifier "$MACOS_APP_ID" \
            target/${{ matrix.target }}/release/zinnia

      - name: Post Build | Prepare artifacts [macOS]
        if: matrix.os == 'macos-latest'
        run: |
          cd target/${{ matrix.target }}/release
          zip ../../../${{ matrix.name }} zinnia

      - name: Release | Upload artifacts
        if: startsWith(github.ref, 'refs/tags/') # Don't create releases when debugging
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          draft: true
          files: ${{ matrix.name }}
          fail_on_unmatched_files: true

      # When debugging this workflow, attach the artifacts to the workflow run
      - name: DEBUGGING | Upload artifacts to workflow run
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

